[package]
name = "assignment1"
version = "0.1.0"
edition = "2021"
authors = ["tanuj"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.3.2"
chrono = "0.4"
clap ={ version = "3.1.6", features = ["derive"] }
